### ISSUE TITLE
Redo tech tree

### ISSUE THREAD

**Issue by darloth** [DaloLorn/Rising-Stars#27]
What do people think of this?  It's a proposal rather than me being hugely upset with how things are, but it'd be a nice opportunity perhaps.

![proposed vague tech layout](https://cloud.githubusercontent.com/assets/8480048/15391925/f13018b4-1dbb-11e6-90e4-9f597f03d8d9.png)

It gives some actual structure to things.

My rationale and goal is to spread things out a little - I'd like to try and separate the different solutions to problems (for example, crystal and niling armor are both very good against someone heavy on the lasers, and right now they're near each other, and also near neutronium.  Liquid armor isn't exactly far either.)

**Comment by DaloLorn** [comment]
That sounds *slightly* like the ABEM grid. Clockwise, it went like this:

Industry/materials, carrier military, military generic, flagship military, energy/shield manipulation, FTL/propulsion (also includes other exotic tech like vacuum telescopes, tachyon sensors and everything star-related), politics, planetary development.

**Comment by Alarcarr** [comment]
We will have to redo the grid at some point and this is a valid scheme .

The only thing to be really carefull about is try to keep  the density of damage /defense techs homogeneous across the grid.

**Comment by darloth** [comment]
Do you have any experience with incentivising weapon specialisation? I'd quite like to encourage more specific weapon choices a bit too.  Perhaps removing most of the +damage to everything modifiers and replacing them with weapon specific modifiers, so people would prefer to mostly design things with one weapon type and then maybe there would be counterdesigns and similar.. .but, I'm not sure how well it would work.  any thoughts?

**Comment by Alarcarr** [comment]
No, but i guess focusing on one type of weapon can be problematic under the current system cause the defenses are unlocked and improved all together.

**Comment by Alarcarr** [comment]
I think I have an iworking path for this , you(@darloth ) can  redo the current tech tree for technicist as they are a special race , and we can experiment on them since they need a special grid anyway.To see how that work out.

**Comment by darloth** [comment]
I have an idea for the weapon balance - leave most of the nodes improving and affecting all types, but lock the basic weapon types behind nodes and distribute appropriately (though close to the base Science node).

Then, at the start of the game give people an event that auto-triggers, that lets them unlock one weapon type for free.

How about something like that?  I think it sortof follows how you also need to unlock Shields, and any other specialist defenses.

Regarding redoing the tech tree for Technist, why do they need their own tree?  But I'll have a go at making a new tree over the next couple of weeks, sure.  No promises it'll be done anytime soon because it's a big chunk of work though, it'll probably miss your first planned release date.

**Comment by DaloLorn** [comment]
Why, indeed...

**Comment by DaloLorn** [comment]
This one's been rendered obsolete by #43, I think.
