### ISSUE TITLE
Fix and finish forcefields.

### ISSUE THREAD

**Issue by DaloLorn** [DaloLorn/Rising-Stars#28]
- [x] Localize the subsystem.
- [x] Finalize balancing.
- [x] Fix a display issue where forcefields make ships think they have a lot more HP than they actually have.
- [x] Find and implement a way for shields to remain viable despite the presence of forcefields.
- [x] Fix an issue where ship HP doesn't update when the forcefield is damaged.
- [x] Art

**Comment by Alarcarr** [comment]
I will try to give them art when they are finnished.

**Comment by DaloLorn** [comment]
Well, aside from balancing and a couple of bugs, it's pretty much functional.

**Comment by Alarcarr** [comment]
How they work I was unable to find the end force-field modifier supposing u made them work like the Bussard Ramjet.

**Comment by DaloLorn** [comment]
Oh no, there's just one emitter (more of a projector, I guess). Scripting a 'proper' Star Trek-style forcefield is beyond my abilities.

**Comment by darloth** [comment]
What is a proper star trek forcefield anyway?

**Comment by DaloLorn** [comment]
Hmm. Now that you mention it, I'm not sure if Star Trek used the 'field projected between two emitters' kind of forcefield in the first place... :o
