### ISSUE TITLE
Different movement physics

### ISSUE THREAD

**Issue by darloth** [DaloLorn/Rising-Stars#29]
So I implemented space-drag earlier tonight, got that working pretty nicely - just needs some tuning of how much extra thrust to provide and how much drag we want.    Would probably add a little turn-speed to rockets at the same time, they just don't have enough.

Generally it makes the movement feel a lot more snappy because the acceleration at lower speeds is much greater, but sublight is soft-capped at a terminal velocity based on the mass to thrust ratio.

I've checked that the movement solver can cope with this, and it can (though come to think of it, I haven't checked supports following flagships with it - it's too late tonight to check that here though.)

Would you like Rising Stars to have slightly draggier physics? They're far less realistic, but I think they're a good chunk more fun and easy to use, plus they give FTL a lot more use.

**Comment by DaloLorn** [comment]
*shrugs*

**Comment by darloth** [comment]
If we're not otherwise touching the Mover I think I can make an entirely compatible separate mod for it, and just use tags to increase the thrust of other engines to compensate for the drag.

Also, I chose to go with linear velocity damping but I could easily make that quadratic, which would then model air/water resistance a lot more closely, and maybe work even better.

I posted it here because I'd -really- like your opinions though.

**Comment by DaloLorn** [comment]
Well, it would certainly make it harder to overshoot your destination.

**Comment by darloth** [comment]
It makes overshooting significantly harder, it makes ships with most of their engines shot out eventually stop flying off into the void, it makes ships you told to turn around half-way through an STL transition actually have a chance of succeeding without flying two starsystems in the direction they were originally going, and it makes even the slower types of FTL much more impactful even on default system spacing settings (which is good because increasing spacing too much makes it really hard to actually play the damn game, the UI doesn't really support it all that well.)

When combined with increased thrust and a bit more turn speed, it produces an experience which still uses physics that are pretty close to newtonian especially at low speeds, but are vastly easier to play with, at least in my opinion.  Plus, I can expose the drag factor so you could have engines that have massive thrust but also lots more drag, producing something akin to arcade space sim physics where you don't drift that much.  With a little bit of work, I could even produce engines that were more/less effective the closer/further away from a star you were.  Basically there's a lot of scope here, and I think that the fact that the movement predictor already built into the game -can- cope with this after all is a fairly big deal.  I'll continue improving my example mod into something people can actually play fun games with, and maybe we can merge it later if anyone has good engine ideas they'd like to see in Rising Stars.

**Comment by DaloLorn** [comment]
Does the drag also affect the ship's angular velocity? I like how derelicts can start spinning around if they were created by explosive ordnance like torpedoes. :P

**Comment by darloth** [comment]
No, it only affects their actual velocity vector.  It'll slow down derelicts or anything else that start moving as a result of an impulse, but it won't stop them spinning.

**Comment by darloth** [comment]
I think this is pretty much done now, as a separate drop-in mod on steam.  Personally I like it, but then I wrote it.  If you'd like it to be core to the abem/rising stars experience that's fine too, but we should decide one way or the other at some point.

**Comment by DaloLorn** [comment]
NMP is now integrated because of the scaling changes I made. It's also toggleable in game configuration, with the exception of lateral thrust, which seemed to have no drawbacks whatsoever (performance notwithstanding, as usual).
