### ISSUE TITLE
Buster machine sucks

### ISSUE THREAD

**Issue by darloth** [DaloLorn/Rising-Stars#34]
It costs 1.5k energy, which is the same as a remnant part that buffs all your ships in some way.

In exchange it.... can't kill a planet before said planet builds a defensive satellite to kill it.

Keep the cost the same because planet-killing on demand should be a big deal.

Make it do a LOT more damage, but quite possibly have longer cooldown.  Aim for 20 seconds to kill a typical planet.  You should upgrade to graviton collapsars not because the buster machine sucks, but because they're more available by the time you get to that tech.

**Comment by DaloLorn** [comment]
It's also ridiculously fragile and short-ranged, IIRC. It can't kill a planet before said planet's support fleet bombs it into oblivion.

**Comment by Alarcarr** [comment]
I updated the buster machine to a Stronger (more HP) design so now will be a lot harder to kil.

**Comment by DaloLorn** [comment]
Yeah, if you could heal planets somehow then I might be in favor of a damage buff. Right now, it'd open the way for raiders similar to carpet bombers.

**Comment by darloth** [comment]
If it has a long cooldown after activation,  it won't open the door to unrestricted raiding because you can't get a lot of these things - they're limited by energy and also artifact occurrence. 

Limited raiding should pretty much be what they are for.

**Comment by darloth** [comment]
That said,  a construction that full healed a planet it exchange for ore would be good too
