### ISSUE TITLE
Rebuild Research Grid.

### ISSUE THREAD

**Issue by DaloLorn** [DaloLorn/Rising-Stars#43]
Right now, the tech grid is something of a messy affair to work with. From a gameplay perspective, it lacks some of the elegance it had in ABEM. From a modding perspective, *we have three grids what the hell whose idea was this how can we sanely maintain three grids?!*

So, first order of business will be to reorganize the tech files, removing a lot of redundancies in the vanilla files (I am not entirely certain why SR2 and WotH need two separate files for what is essentially the same tech) and introducing some order into the file structure.

- [x] Remove duplicate techs. Use WotH and WotH-derived files where possible, unless our WotH grid uses their corresponding base files by mistake... which seems to be the case for Bulkheads at the very least.
- [x] Rebuild file structure, using blank files to deactivate the appropriate vanilla files. (This has instead been achieved by altering the research loader and editor scripts.)

After the files are patched up, the next step will be to edit all the relevant scripts so that the same tech grid is loaded regardless of whether WotH is enabled. Once that's done, we can start figuring out how it should look.

- [ ] Hybridize Technocracy with the base tech system. I am not sure how we should do this, but Technocracy needs this just as much as the non-WotH grid does.
- [x] Divide the grid into clearly defined segments - kind of like ABEM, but without the high density, that was a leftover from the vanilla grid of its time.
- [x] Maybe add some of the old ABEM things, like specializations. (Except, you know, more than one of them. It always bugged me that we had all those interesting ideas but never fleshed them out properly.)
- [x] Adjust "DLC Replace" entries for WotH-only techs to be either link nodes or empty, depending on where they are in the grid. (The 'empty' variant may require some rewiring on my part.)

**Comment by DaloLorn** [comment]
This is basically done. Sadly, I can't think of a way to keep Technocracy alive, so it'll be going away entirely.

**Comment by EngineOfDarkness** [comment]
>...can't think of a way to keep Technocracy alive, so it'll be going away entirely

That sucks, my faourite Government Form. No more Technocrazy (not a typo) preset for me I guess :(

*Insert Dart Vader "NOOOO" pic here*

Oh well, I'll live
