### ISSUE TITLE
Floating Popups not being saved properly

### ISSUE THREAD

**Issue by EngineOfDarkness** [DaloLorn/Rising-Stars#54]
You might want to take a look at merging this to make floating popups persist in savegames (currently they don't, neither in vanilla 2.0.3 WotH nor Rising Stars)

https://github.com/EngineOfDarkness/star-ruler-2-woth-unofficial-enhancements/commit/db8b0ccd08cc59d2192bbb5d2006316e31d828eb

For Details on this see: https://github.com/EngineOfDarkness/star-ruler-2-woth-unofficial-enhancements/issues/1

Be wary though that existing savegames will not load properly and a fresh game is required.

**Comment by DaloLorn** [comment]
Heh, took me far too long to figure out what the hell you were talking about.

I'm getting ready to commit the fix as I speak, just as soon as SourceTree wakes up, so this can probably be closed now.

**Comment by EngineOfDarkness** [comment]
Ah yeah, should've probably said I made a video comparison unfixed/fixed , sorry.
