### ISSUE TITLE
Harvester capabilities do not scale with size

### ISSUE THREAD

**Issue by TheNumenorean** [DaloLorn/Rising-Stars#55]
A harvester of size 10k and a 40% larger harvester tool by number of hexes than the default still operates at the same functionality and speed as the default.

**Comment by DaloLorn** [comment]
Working as intended. Harvesters need to be bigger for their own safety and to mine barren planets faster, but improving the rate at which they can mark a planet for harvesting would inevitably result in a scenario where the ship could fly in, tag each planet, and fly out in a minute or two.

**Comment by TheNumenorean** [comment]
Marking planets makes sense. They don't seem to mine barren planets faster though.

**Comment by DaloLorn** [comment]
*sighs* That may be because that's exactly what it does...

Fixed it internally, I'll try to push it to the Workshop when I get back from college this evening.
