### ISSUE TITLE
Rework cargo system.

### ISSUE THREAD

**Issue by DaloLorn** [DaloLorn/Rising-Stars#56]
Writing down a system outline to work from:

- [x] Find a better name?
- [x] Global Resources:
  - [x] Accessible from anywhere in the empire, and displayed in the resource UI.
  - [x] Most cargo resources are used like this. Ore for starship construction, the Herald things for Beacon upgrades, and possibly others that may be introduced in the future. However, racial resources such as Herald Support are only visible to Heralds or empires which have somehow gained a supply of that resource.
  - [x] Can be traded via the diplomacy system, in the same fashion as money or energy.
- [x] Local Resources: 
  - [x] Raw materials or custom-allocated resources, not visible in the resource UI.
  - [x] Raw materials must be transferred to a planet (or Mothership?) to be stored in the global pool. Ore is an example of this - miners mine asteroids as before, and the Ore is stored in the global pool once it reaches the planet.
  - [x] Base Materials, being tied into the import/export system, are still used locally. (Optionally, we could allow Transmuters to transfer Base Materials into the global pool when they aren't exporting to other planets - the local pool would be prioritized for resource consumption, but you could let various planets shut down at random when you started losing Transmuters.)

**Comment by EngineOfDarkness** [comment]
Sounds interesting, certainly does away the annoying micromanagement regarding resources (ore for that matter).

I was going to write down my own idea how this could work and cause some emergend gameplay, but I noticed this was off the chart crazy with regards to the required work and possible edge cases which are involved...
